"""Generator for devenv.nix files."""
from __future__ import annotations

from textwrap import dedent

from nix_devenv_wrapper.models import FlakeConfig


def generate_devenv_nix(config: FlakeConfig) -> str:
    """Generate a devenv.nix file based on the configuration."""
    extra_packages = "\n    ".join(config.runtime.extra_packages)
    extra_packages_section = f"\n    {extra_packages}" if extra_packages else ""

    return dedent(
        f"""\
        # devenv.nix - auto-generated by nix-devenv-wrapper
        {{ pkgs, lib, config, inputs, ... }}:

        {{
          packages = with pkgs; [
            nixpkgs-fmt
            nix-prefetch-git
            cachix{extra_packages_section}
          ];

          languages.python = {{
            enable = true;
            uv = {{
              enable = true;
              sync.enable = true;
            }};
          }};

          pre-commit.hooks = {{
            nixpkgs-fmt.enable = true;
          }};

          scripts = {{
            check-update.exec = "uv run scripts/check_update.py";
            update-version.exec = "uv run scripts/update_version.py $@";
            build.exec = "nix build --print-build-logs";
            test-build.exec = ''
              nix build --print-build-logs
              ./result/bin/{config.wrapper.binary_name} --version
            '';
          }};

          enterShell = ''
            echo ""
            echo "🔧 Development environment ready"
            echo ""
            echo "Commands:"
            echo "  check-update   - Check for new upstream versions"
            echo "  update-version - Update to latest (or specify version)"
            echo "  build          - Build the nix package"
            echo "  test-build     - Build and verify version output"
            echo ""
          '';
        }}
        """
    )
