"""Generator for flake.nix files."""
from __future__ import annotations

from textwrap import dedent

from nix_devenv_wrapper.models import FlakeConfig


def generate_flake_nix(config: FlakeConfig) -> str:
    """Generate a flake.nix file based on the configuration."""
    description = f"Nix wrapper package for {config.source.name}"
    overlay_name = config.flake_name
    binary_name = config.wrapper.binary_name

    devenv_section = ""
    if config.devenv_enabled:
        devenv_section = """
        devShells.default = devenv.lib.mkShell {
          inherit inputs pkgs;
          modules = [ ./devenv.nix ];
        };"""

    return dedent(
        f"""\
        # flake.nix - auto-generated by nix-devenv-wrapper
        {{
          description = "{description}";

          inputs = {{
            nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
            flake-utils.url = "github:numtide/flake-utils";
            devenv.url = "github:cachix/devenv";
          }};

          nixConfig = {{
            extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
            extra-substituters = "https://devenv.cachix.org";
          }};

          outputs = {{ self, nixpkgs, flake-utils, devenv }}@inputs:
            let
              overlay = final: prev: {{
                {overlay_name} = final.callPackage ./package.nix {{ }};
              }};
            in
            flake-utils.lib.eachDefaultSystem (system:
              let
                pkgs = import nixpkgs {{
                  inherit system;
                  config.allowUnfree = true;
                  overlays = [ overlay ];
                }};
              in
              {{
                packages = {{
                  default = pkgs.{overlay_name};
                  {overlay_name} = pkgs.{overlay_name};
                }};

                apps = {{
                  default = {{
                    type = "app";
                    program = "${{pkgs.{overlay_name}}}/bin/{binary_name}";
                  }};
                }};
                {devenv_section}
              }}) // {{
                overlays.default = overlay;
              }};
        }}
        """
    )
